languageCode:           "en"
title:                  "EnergySage Design System"
baseURL:                ""
enableInlineShortcodes: true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/0.1/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/0.1/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/0.1/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "EnergySages base design system, based on Bootstrap 4."
  authors:              "Tom Leo, Ryan Mulready, and EnergySage contributors"
  social_image_path:    /docs/0.1/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/0.1/assets/brand/bootstrap-social-logo.png

  current_version:      "0.1.4"
  current_ruby_version: "0.1.4"
  docs_version:         "0.1"
  rfs_version:          "v8.1.0"
  slack:                "https://bootstrap-slack.herokuapp.com/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  expo:                 "https://expo.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"
  github_org:           "https://github.com/EnergySage"
  repo:                 "https://github.com/EnergySage/es-bs-base"
  twitter:              "EnergySage"

  download:
    source:             "https://github.com/EnergySage/es-bs-base/archive/v0.1.4.zip"
    dist:               "https://github.com/EnergySage/es-bs-base/releases/download/v0.1.4/bootstrap0.1.4-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/es-bs-base@0.1.1/dist/css/bootstrap.min.css"
    css_hash:         "sha384-/HzsDxor0D2Kr3OmJOdJ/6NGC9/5ADDEXmBATS6Q4lmVlfc+W69bDSevZ1oXXpnL"
    js:               "https://cdn.jsdelivr.net/npm/es-bs-base@0.1.1/dist/js/bootstrap.min.js"
    js_hash:          "sha384-KhGMI2rr+uieC/dtjtEIGnWEYUVX2rTfrYNmbs1e9KRIMhqLgkieWQg21wgtFAOy"
    js_bundle:        "https://cdn.jsdelivr.net/npm/es-bs-base@0.1.1/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-pFYFlFVM2uMzFqccWErbBh01cCd+m6rRHxT7XjvHbyWej7S7g2w8tDlSFuxoRrSc"
    jquery:           "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    jquery_hash:      "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    popper_hash:      "sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
